[package]
name = "mintest-impl"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "^1.0.5"
quote = "^1.0.2"
syn = "^1.0.5"

[features]
unstable = []
unstable-test = []
test = []
